create table person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    year_of_birth int NOT NULL
);


create table book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES person(id) ON DELETE SET NULL,
    title varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year int NOT NULL
)